# -*- coding: utf-8 -*-
"""Risk Alert Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zWOXHDhExMRi3KK1dXwEdfCvDDB4Ptx

# **Part A: Conceptual Understanding (Theory)**
**Q1. What is Logistic Regression and why is it suitable for classification?**

Answer:

Logistic Regression is a supervised machine learning algorithm used for binary classification problems. It predicts the probability of an instance belonging to a particular class using the sigmoid function. It is suitable for classification because its output lies between 0 and 1, making it ideal for predicting categorical outcomes such as High Risk or Low Risk.

**Q2. Explain classification performance metrics and why accuracy alone is insufficient.**

Answer:

Classification metrics evaluate the effectiveness of a classification model. Accuracy measures overall correctness, but it may be misleading when classes are imbalanced. Metrics such as Precision, Recall, F1-Score, and ROC-AUC provide a more complete assessment, especially for minority classes.

**Q3. Define Type-I Error and Type-II Error.**

Answer:

Type-I Error (False Positive): Predicting a customer as high risk when they are actually low risk.
Type-II Error (False Negative): Predicting a customer as low risk when they are actually high risk.

In banking, minimizing Type-II errors is crucial because missing a risky customer can lead to financial losses.

**Q4. Explain Precision, Recall, F1-Score, TPR, and FPR.**

Answer:

Precision: Percentage of predicted positive cases that are actually positive.
Recall (TPR): Percentage of actual positive cases correctly identified.
F1-Score: Harmonic mean of Precision and Recall.
True Positive Rate (TPR): Same as Recall.
False Positive Rate (FPR): Percentage of negative cases incorrectly classified as positive.

**Q5. What is AUC-ROC and how does it help?**

Answer:

The ROC curve plots the True Positive Rate against the False Positive Rate at different thresholds. The AUC (Area Under the Curve) summarizes the model's ability to distinguish between classes. A higher AUC indicates better classification performance.

**Q6. Why does imbalanced data create problems in classification models?**

Answer:

Imbalanced datasets contain significantly more samples of one class than another. Models trained on such data tend to favor the majority class, resulting in poor detection of minority class instances. Techniques like SMOTE, ADASYN, and resampling help address this issue.

# **Part B: Dataset Understanding & Preparation**

**Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer

"""**Upload Dataset**"""

df = pd.read_excel("Risk_Alert_Classifier_Dataset_4600.xlsx")

"""**Display Dataset**"""

df.head()

"""**Dataset Shape**"""

print(df.shape)

"""**Dataset Information**"""

df.info()

"""**Missing Values**"""

df.isnull().sum()

"""**Duplicate Records**"""

df.duplicated().sum()

"""**Statistical Summary**"""

df.describe(include="all")

"""**Convert Date Column (if present)**"""

df.info()

"""**Encode Categorical Columns**"""

from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col].astype(str))

"""**Convert Date Columns**"""

date_columns = df.select_dtypes(include=['datetime64[ns]', 'datetime64']).columns

for col in date_columns:
    df[col] = pd.to_datetime(df[col])

    df[col + '_year'] = df[col].dt.year
    df[col + '_month'] = df[col].dt.month
    df[col + '_day'] = df[col].dt.day

# Drop original datetime columns
df.drop(columns=date_columns, inplace=True)

label_encoder = LabelEncoder()

cat_cols = df.select_dtypes(include=['object','category']).columns

for col in cat_cols:
    df[col] = df[col].astype(str)
    df[col] = label_encoder.fit_transform(df[col])

"""**KNN Imputation**"""

imputer = KNNImputer(n_neighbors=5)

df = pd.DataFrame(
    imputer.fit_transform(df),
    columns=df.columns
)

print("Missing Values After Imputation")
print(df.isnull().sum())

print("\nDataset Shape:", df.shape)

"""**Features and Target**"""

X = df.drop("risk_status", axis=1)
y = df["risk_status"]

"""**Check Class Distribution**"""

print(y.value_counts())

"""**Train-Test Split (Maintain Class Distribution)**"""

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=42, stratify=y)

"""**Feature Scaling**"""

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""**Correlation Heatmap**"""

plt.figure(figsize=(10,8))

plt.imshow(df.corr(), cmap='coolwarm', aspect='auto')

plt.colorbar()

plt.xticks(range(len(df.columns)), df.columns, rotation=90)

plt.yticks(range(len(df.columns)), df.columns)

plt.title("Correlation Heatmap")

plt.tight_layout()

plt.show()

"""**Class Distribution Plot**"""

plt.figure(figsize=(6,4))

y.value_counts().plot(kind='bar')

plt.title("Risk Status Distribution")

plt.xlabel("Risk Status")

plt.ylabel("Count")

plt.show()

"""**Save Cleaned Dataset (Optional)**"""

df.to_csv("cleaned_risk_dataset.csv", index=False)

"""# **Part C: Baseline Classification Model (Logistic Regression)**

**Import Required Libraries**
"""

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import ( accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_curve, roc_auc_score)

import matplotlib.pyplot as plt

"""**Create Features and Target**"""

X = df.drop("risk_status", axis=1)
y = df["risk_status"]

"""**Train-Test Split**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)

"""**Feature Scaling**"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""**Train Logistic Regression**"""

log_model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

log_model.fit(X_train_scaled, y_train)

"""**Predictions**"""

y_pred = log_model.predict(X_test_scaled)

y_prob = log_model.predict_proba(X_test_scaled)[:,1]

"""**Accuracy**"""

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

"""**Precision**"""

precision = precision_score(y_test, y_pred)

print("Precision :", precision)

"""**Recall**"""

recall = recall_score(y_test, y_pred)

print("Recall :", recall)

"""**F1 Score**"""

f1 = f1_score(y_test, y_pred)

print("F1 Score :", f1)

"""**Confusion Matrix**"""

cm = confusion_matrix(y_test, y_pred)

print(cm)

"""**Display Confusion Matrix**"""

plt.figure(figsize=(5,5))

plt.imshow(cm, cmap="Blues")

plt.title("Confusion Matrix")

plt.colorbar()

plt.xticks([0,1],["Low Risk","High Risk"])

plt.yticks([0,1],["Low Risk","High Risk"])

plt.xlabel("Predicted")

plt.ylabel("Actual")

for i in range(2):
    for j in range(2):
        plt.text(j,i,str(cm[i,j]),ha='center',va='center',fontsize=12)

plt.show()

"""**Classification Report**"""

print(classification_report(y_test, y_pred))

"""**Calculate Type-I and Type-II Errors**"""

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

print("True Positives :", tp)
print("True Negatives :", tn)
print("False Positives (Type-I Error) :", fp)
print("False Negatives (Type-II Error) :", fn)

"""**ROC Curve**"""

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure(figsize=(6,6))

plt.plot(fpr, tpr, label="Logistic Regression")

plt.plot([0,1],[0,1],'r--')

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve")

plt.legend()

plt.show()

"""**AUC Score**"""

auc = roc_auc_score(y_test, y_prob)

print("AUC Score :", auc)

"""**Performance Summary Table**"""

performance = {
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "AUC": auc
}

summary = pd.DataFrame(performance, index=["Logistic Regression"])

summary

"""**Install imbalanced-learn**"""

!pip install imbalanced-learn

"""**Import Libraries**"""

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import ADASYN

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

"""**Check Original Class Distribution**"""

print("Original Class Distribution")

print(y_train.value_counts())

"""**Plot Original Distribution**"""

plt.figure(figsize=(6,4))

y_train.value_counts().plot(kind='bar')

plt.title("Original Class Distribution")

plt.xlabel("Risk Class")

plt.ylabel("Count")

plt.show()

"""**Apply Under Sampling**"""

rus = RandomUnderSampler(random_state=42)

X_under, y_under = rus.fit_resample(
    X_train_scaled,
    y_train
)

"""**Check Distribution**"""

print(y_under.value_counts())

"""**Train Logistic Regression**"""

under_model = LogisticRegression(max_iter=1000)

under_model.fit(X_under,y_under)

under_pred = under_model.predict(X_test_scaled)

"""**Evaluate**"""

under_accuracy = accuracy_score(
    y_test,
    under_pred
)

under_precision = precision_score(
    y_test,
    under_pred
)

under_recall = recall_score(
    y_test,
    under_pred
)

under_f1 = f1_score(
    y_test,
    under_pred
)

print("Accuracy :",under_accuracy)

print("Precision :",under_precision)

print("Recall :",under_recall)

print("F1 :",under_f1)

"""**Random Over Sampling**"""

ros = RandomOverSampler(random_state=42)

X_over,y_over = ros.fit_resample(
    X_train_scaled,
    y_train
)

print(y_over.value_counts())

"""**Train Model**"""

over_model = LogisticRegression(max_iter=1000)

over_model.fit(
    X_over,
    y_over
)

over_pred = over_model.predict(
    X_test_scaled
)

"""**Evaluate**"""

over_accuracy = accuracy_score(
    y_test,
    over_pred
)

over_precision = precision_score(
    y_test,
    over_pred
)

over_recall = recall_score(
    y_test,
    over_pred
)

over_f1 = f1_score(
    y_test,
    over_pred
)

print("Accuracy :",over_accuracy)

print("Precision :",over_precision)

print("Recall :",over_recall)

print("F1 :",over_f1)

"""**SMOTE**"""

smote = SMOTE(random_state=42)

X_smote,y_smote = smote.fit_resample(
    X_train_scaled,
    y_train
)

print(y_smote.value_counts())

"""**Train Model**"""

smote_model = LogisticRegression(max_iter=1000)

smote_model.fit(
    X_smote,
    y_smote
)

smote_pred = smote_model.predict(
    X_test_scaled
)

"""**Evaluate**"""

smote_accuracy = accuracy_score(
    y_test,
    smote_pred
)

smote_precision = precision_score(
    y_test,
    smote_pred
)

smote_recall = recall_score(
    y_test,
    smote_pred
)

smote_f1 = f1_score(
    y_test,
    smote_pred
)

print("Accuracy :",smote_accuracy)

print("Precision :",smote_precision)

print("Recall :",smote_recall)

print("F1 :",smote_f1)

"""**ADASYN**"""

adasyn = ADASYN(random_state=42)

X_ada,y_ada = adasyn.fit_resample(
    X_train_scaled,
    y_train
)

print(y_ada.value_counts())

"""**Train Model**"""

ada_model = LogisticRegression(max_iter=1000)

ada_model.fit(
    X_ada,
    y_ada
)

ada_pred = ada_model.predict(
    X_test_scaled
)

"""**Evaluate**"""

ada_accuracy = accuracy_score(
    y_test,
    ada_pred
)

ada_precision = precision_score(
    y_test,
    ada_pred
)

ada_recall = recall_score(
    y_test,
    ada_pred
)

ada_f1 = f1_score(
    y_test,
    ada_pred
)

print("Accuracy :",ada_accuracy)

print("Precision :",ada_precision)

print("Recall :",ada_recall)

print("F1 :",ada_f1)

"""**Compare All Sampling Techniques**"""

sampling_results = pd.DataFrame({

'Sampling Method':[
'Original',
'Random Under Sampling',
'Random Over Sampling',
'SMOTE',
'ADASYN'
],

'Accuracy':[
accuracy,
under_accuracy,
over_accuracy,
smote_accuracy,
ada_accuracy
],

'Precision':[
precision,
under_precision,
over_precision,
smote_precision,
ada_precision
],

'Recall':[
recall,
under_recall,
over_recall,
smote_recall,
ada_recall
],

'F1 Score':[
f1,
under_f1,
over_f1,
smote_f1,
ada_f1
]

})

sampling_results

"""**Plot Comparison**"""

plt.figure(figsize=(10,5))

plt.bar(
sampling_results['Sampling Method'],
sampling_results['F1 Score']
)

plt.xticks(rotation=20)

plt.ylabel("F1 Score")

plt.title("Sampling Technique Comparison")

plt.show()

"""**Best Sampling Technique**"""

best_sampling = sampling_results.loc[
sampling_results['F1 Score'].idxmax()
]

print(best_sampling)

"""# **Part E: Decision Tree Classifier & Hyperparameter Tuning**"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import ( accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_curve, roc_auc_score)

"""**Train Decision Tree**"""

dt = DecisionTreeClassifier(
    random_state=42
)

dt.fit(X_train, y_train)

"""**Predictions**"""

dt_pred = dt.predict(X_test)

dt_prob = dt.predict_proba(X_test)[:,1]

"""**Performance Metrics**"""

dt_accuracy = accuracy_score(y_test, dt_pred)

dt_precision = precision_score(y_test, dt_pred)

dt_recall = recall_score(y_test, dt_pred)

dt_f1 = f1_score(y_test, dt_pred)

print("Accuracy :",dt_accuracy)

print("Precision :",dt_precision)

print("Recall :",dt_recall)

print("F1 Score :",dt_f1)

"""**Confusion Matrix**"""

cm = confusion_matrix(y_test,dt_pred)

print(cm)

"""**Display Confusion Matrix**"""

plt.figure(figsize=(5,5))

plt.imshow(cm,cmap='Blues')

plt.colorbar()

plt.title("Decision Tree Confusion Matrix")

plt.xlabel("Predicted")

plt.ylabel("Actual")

for i in range(2):
    for j in range(2):
        plt.text(j,i,str(cm[i,j]),ha='center',va='center')

plt.show()

"""**Classification Report**"""

print(classification_report(y_test,dt_pred))

"""**Hyperparameter Tuning**"""

param_grid = {

'criterion':['gini','entropy'],

'max_depth':[5,10,15,20,None],

'min_samples_split':[2,5,10],

'min_samples_leaf':[1,2,4]

}

grid_dt = GridSearchCV(

DecisionTreeClassifier(random_state=42),

param_grid,

cv=5,

scoring='f1',

n_jobs=-1

)

grid_dt.fit(X_train,y_train)

print(grid_dt.best_params_)

"""**Best Decision Tree**"""

best_dt = grid_dt.best_estimator_

best_dt.fit(X_train,y_train)

best_pred = best_dt.predict(X_test)

best_prob = best_dt.predict_proba(X_test)[:,1]

"""**Best Model Performance**"""

best_accuracy = accuracy_score(y_test,best_pred)

best_precision = precision_score(y_test,best_pred)

best_recall = recall_score(y_test,best_pred)

best_f1 = f1_score(y_test,best_pred)

print("Accuracy :",best_accuracy)

print("Precision :",best_precision)

print("Recall :",best_recall)

print("F1 :",best_f1)

"""**ROC Curve**"""

fpr,tpr,_ = roc_curve(y_test,best_prob)

plt.figure(figsize=(6,6))

plt.plot(fpr,tpr,label="Decision Tree")

plt.plot([0,1],[0,1],'r--')

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve")

plt.legend()

plt.show()

"""**AUC Score**"""

auc = roc_auc_score(y_test,best_prob)

print("AUC :",auc)

"""**Feature Importance**"""

importance = pd.DataFrame({

'Feature':X.columns,

'Importance':best_dt.feature_importances_

})

importance = importance.sort_values(

by='Importance',

ascending=False

)

importance

"""**Feature Importance Plot**"""

plt.figure(figsize=(10,6))

plt.barh(

importance['Feature'],

importance['Importance']

)

plt.gca().invert_yaxis()

plt.title("Feature Importance")

plt.xlabel("Importance")

plt.show()

"""**Actual vs Predicted Comparison**"""

comparison = pd.DataFrame({

'Actual':y_test.values,

'Predicted':best_pred

})

comparison.head(20)

"""**Save Best Model (Optional)**"""

import joblib

joblib.dump(best_dt,'decision_tree_model.pkl')

"""# **Part F: Random Forest Classifier & Hyperparameter Tuning**

**Import Libraries**
"""

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import ( accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_curve, roc_auc_score)

"""**Train Random Forest Classifier**"""

rf = RandomForestClassifier(
    random_state=42,
    n_estimators=100
)

rf.fit(X_train, y_train)

"""**Predictions**"""

rf_pred = rf.predict(X_test)

rf_prob = rf.predict_proba(X_test)[:,1]

"""**Performance Metrics**"""

rf_accuracy = accuracy_score(y_test, rf_pred)

rf_precision = precision_score(y_test, rf_pred)

rf_recall = recall_score(y_test, rf_pred)

rf_f1 = f1_score(y_test, rf_pred)

print("Accuracy :", rf_accuracy)

print("Precision :", rf_precision)

print("Recall :", rf_recall)

print("F1 Score :", rf_f1)

"""**Confusion Matrix**"""

rf_cm = confusion_matrix(y_test, rf_pred)

print(rf_cm)

"""**Display Confusion Matrix**"""

plt.figure(figsize=(5,5))

plt.imshow(rf_cm, cmap='Greens')

plt.title("Random Forest Confusion Matrix")

plt.colorbar()

plt.xlabel("Predicted")

plt.ylabel("Actual")

for i in range(2):
    for j in range(2):
        plt.text(j, i, str(rf_cm[i,j]), ha='center', va='center')

plt.show()

"""**Classification Report**"""

print(classification_report(y_test, rf_pred))

"""**Hyperparameter Tuning**"""

param_grid = {

    'n_estimators':[100,200,300],

    'max_depth':[10,20,None],

    'min_samples_split':[2,5,10],

    'min_samples_leaf':[1,2,4]

}

grid_rf = GridSearchCV(

    RandomForestClassifier(random_state=42),

    param_grid,

    cv=5,

    scoring='f1',

    n_jobs=-1

)

grid_rf.fit(X_train, y_train)

print("Best Parameters")

print(grid_rf.best_params_)

"""**Best Random Forest Model**"""

best_rf = grid_rf.best_estimator_

best_rf.fit(X_train, y_train)

best_rf_pred = best_rf.predict(X_test)

best_rf_prob = best_rf.predict_proba(X_test)[:,1]

"""**Evaluate Best Model**"""

best_rf_accuracy = accuracy_score(y_test, best_rf_pred)

best_rf_precision = precision_score(y_test, best_rf_pred)

best_rf_recall = recall_score(y_test, best_rf_pred)

best_rf_f1 = f1_score(y_test, best_rf_pred)

print("Accuracy :", best_rf_accuracy)

print("Precision :", best_rf_precision)

print("Recall :", best_rf_recall)

print("F1 Score :", best_rf_f1)

"""**ROC Curve**"""

fpr, tpr, thresholds = roc_curve(y_test, best_rf_prob)

plt.figure(figsize=(6,6))

plt.plot(fpr, tpr, label="Random Forest")

plt.plot([0,1],[0,1],'r--')

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve")

plt.legend()

plt.show()

"""**AUC Score**"""

rf_auc = roc_auc_score(y_test, best_rf_prob)

print("AUC Score :", rf_auc)

"""**Feature Importance**"""

importance = pd.DataFrame({

    'Feature': X.columns,

    'Importance': best_rf.feature_importances_

})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

importance

"""**Feature Importance Plot**"""

plt.figure(figsize=(10,6))

plt.barh(
    importance['Feature'],
    importance['Importance']
)

plt.gca().invert_yaxis()

plt.title("Random Forest Feature Importance")

plt.xlabel("Importance Score")

plt.show()

"""**Actual vs Predicted**"""

comparison = pd.DataFrame({

    'Actual': y_test.values,

    'Predicted': best_rf_pred

})

comparison.head(20)

"""**Save Model**"""

import joblib

joblib.dump(best_rf, "Random_Forest_Model.pkl")

"""**Summary Table**"""

rf_results = pd.DataFrame({

    'Metric':['Accuracy','Precision','Recall','F1 Score','AUC'],

    'Value':[

        best_rf_accuracy,

        best_rf_precision,

        best_rf_recall,

        best_rf_f1,

        rf_auc

    ]

})

rf_results

"""# **Part G: Model Comparison & Performance Analysis**

**Create Performance Comparison Table**
"""

comparison = pd.DataFrame({

    'Model':[
        'Logistic Regression',
        'Decision Tree',
        'Random Forest'
    ],

    'Accuracy':[
        accuracy,
        best_accuracy,
        best_rf_accuracy
    ],

    'Precision':[
        precision,
        best_precision,
        best_rf_precision
    ],

    'Recall':[
        recall,
        best_recall,
        best_rf_recall
    ],

    'F1 Score':[
        f1,
        best_f1,
        best_rf_f1
    ],

    'AUC':[
        auc,
        auc,
        rf_auc
    ]

})

comparison

"""**Accuracy Comparison**"""

plt.figure(figsize=(8,5))

plt.bar(
    comparison['Model'],
    comparison['Accuracy']
)

plt.title("Accuracy Comparison")

plt.ylabel("Accuracy")

plt.xticks(rotation=15)

plt.show()

"""**Precision Comparison**"""

plt.figure(figsize=(8,5))

plt.bar(
    comparison['Model'],
    comparison['Precision']
)

plt.title("Precision Comparison")

plt.ylabel("Precision")

plt.xticks(rotation=15)

plt.show()

"""**Recall Comparison**"""

plt.figure(figsize=(8,5))

plt.bar(
    comparison['Model'],
    comparison['Recall']
)

plt.title("Recall Comparison")

plt.ylabel("Recall")

plt.xticks(rotation=15)

plt.show()

"""**F1 Score Comparison**"""

plt.figure(figsize=(8,5))

plt.bar(
    comparison['Model'],
    comparison['F1 Score']
)

plt.title("F1 Score Comparison")

plt.ylabel("F1 Score")

plt.xticks(rotation=15)

plt.show()

"""**AUC Comparison**"""

plt.figure(figsize=(8,5))

plt.bar(
    comparison['Model'],
    comparison['AUC']
)

plt.title("AUC Comparison")

plt.ylabel("AUC")

plt.xticks(rotation=15)

plt.show()

"""**Combined ROC Curve**"""

plt.figure(figsize=(8,6))

# Logistic Regression
fpr_log, tpr_log, _ = roc_curve(y_test, y_prob)
plt.plot(fpr_log, tpr_log, label='Logistic Regression')

# Decision Tree
fpr_dt, tpr_dt, _ = roc_curve(y_test, best_prob)
plt.plot(fpr_dt, tpr_dt, label='Decision Tree')

# Random Forest
fpr_rf, tpr_rf, _ = roc_curve(y_test, best_rf_prob)
plt.plot(fpr_rf, tpr_rf, label='Random Forest')

plt.plot([0,1],[0,1],'k--')

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve Comparison")

plt.legend()

plt.show()

"""**Confusion Matrix Comparison**"""

print("Logistic Regression")
print(confusion_matrix(y_test, y_pred))

print("\nDecision Tree")
print(confusion_matrix(y_test, best_pred))

print("\nRandom Forest")
print(confusion_matrix(y_test, best_rf_pred))

"""**Best Model Selection**"""

best_model = comparison.loc[
    comparison['F1 Score'].idxmax()
]

print("Best Performing Model")

print(best_model)

"""**Save Comparison**"""

comparison.to_csv(
    "Model_Comparison.csv",
    index=False
)

"""**Summary**"""

print(comparison)

"""# **Part H: Final Report, Conclusion & Future Scope**

**Conclusion**

This project developed a Risk Alert Classifier using machine learning techniques to predict customer risk levels. Data preprocessing, KNN imputation, and feature scaling were performed before training the models. Logistic Regression, Decision Tree, and Random Forest classifiers were implemented and evaluated using Accuracy, Precision, Recall, F1-Score, and AUC-ROC. Different sampling techniques (Random Under Sampling, Random Over Sampling, SMOTE, and ADASYN) were also applied to handle class imbalance. Based on the evaluation results, the model with the highest F1-Score and AUC was selected as the best-performing model.

**Key Findings**

Data preprocessing improved data quality.
Sampling techniques helped balance the dataset.
Random Forest generally provided the best classification performance.
F1-Score and AUC were the most reliable metrics for evaluating the imbalanced dataset.
"""